
function []=GUI1(fileName, fileType)
f = figure ('menu','none',...
    'Position', [950 450 650 520],...
    'visible','off');
set(f,'name','Peak Detection Parameters','numbertitle','off')
 
 
%% spacing of objects
 
xText1Pos=20;
yText1Pos=470;
xText1Siz=95;
yText1Siz=40;
spaceText1=60;

x2Pos=220;
y2Pos=465;
y2space=50;
 
xInput1Pos=120;
yInput1Pos=470;
xInput1Siz=50;
yInput1Siz=40;
spaceText1=60;

 
%% make labels for the input boxes
 
txtFt=uicontrol('Style','text',...
    'Position',[xText1Pos+250,yText1Pos,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','File Type');
 
txtBsln=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','# of Baseline Frames');
 
txtPeak=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-2*spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','# of Peak Frames');
 
txtNoise=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-3*spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','Noise Multiplier');
 
txtDlyGap=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-4*spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
	'String','Delay Gap Length');
 
txtDly=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-5*spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','# of Delay Frames');
 
txtDlyNoise=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-6*spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','Delay Noise Multiplier');
 
prevBL=uicontrol('Style','text',...
    'Position',[xText1Pos,yText1Pos-7*spaceText1,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','# Previous frames');

txtChanL(1)=uicontrol('Style','text',...
    'Position',[xInput1Pos-20,yText1Pos,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','Channel 1 (left)');

txtChanR(2)=uicontrol('Style','text',...
    'Position',[xInput1Pos+60,yText1Pos,xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','Channel 2 (right)');
 
%% Create the fields for parameter inputs
 
FTypeinput=uicontrol('Style','edit',...
    'Position',[xInput1Pos+250 yInput1Pos xInput1Siz+40 yInput1Siz],...
    'FontSize', 14,...
    'String', fileType);
 
PeakDBL1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','23');

PeakDBL2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','23');
 
PeakDPk1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-2*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','8');

PeakDPk2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-2*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','8');
 
NoiseMul1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-3*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','1.4');

NoiseMul2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-3*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','1.6');
 
peakDetDelay1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-4*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','20');

peakDetDelay2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-4*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','20');
 
peakDetPostBL1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-5*spaceText1 xInput1Siz yInput1Siz],...
	'FontSize', 14,...
    'String','21');
 
peakDetPostBL2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-5*spaceText1 xInput1Siz yInput1Siz],...
	'FontSize', 14,...
    'String','21');

NoiseMulDelay1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-6*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','1.5');
 
NoiseMulDelay2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-6*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','1.6');

prevBaseline1=uicontrol('Style','edit',...
    'Position',[xInput1Pos yInput1Pos-7*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','10');

prevBaseline2=uicontrol('Style','edit',...
    'Position',[xInput1Pos+80 yInput1Pos-7*spaceText1 xInput1Siz yInput1Siz],...
    'FontSize', 14,...
    'String','10');
 
f.Visible='on';
 
%% Make checkboxes
 
%BkgndCorBtn=uicontrol('Style','checkbox','String','Use Baseline Correction',...
%	'FontSize', 14,...
%	'Position', [xText1Pos+x2Pos y2Pos 200 20]);
 
PlotA=uicontrol('Style','checkbox','String','Plot Traces',...
    'FontSize', 14,...
    'Position', [xText1Pos+x2Pos+150 y2Pos-25 200 20]);
set(PlotA, 'Value',1);
 
Histo=uicontrol('Style','checkbox','String','Plot Histograms',...
    'FontSize', 14,...
    'Position', [xText1Pos+x2Pos+150 y2Pos-y2space-10 200 20]);
set(Histo, 'Value',1);
 
 
%% Make file name input
 
fileNameTxt=uicontrol('Style','text',...
    'Position',[xText1Pos+x2Pos+40 y2Pos-(2*y2space+15),xText1Siz,yText1Siz],...
    'FontSize', 14,...
    'String','File Name:');
 
fileName=uicontrol('Style','edit',...
    'Position',[xText1Pos+x2Pos+150 y2Pos-(2*y2space+00) xInput1Siz+100 yInput1Siz-10],...
    'FontSize', 14,...
    'String',fileName);

%% Make channel checkboxes
 
%BkgndCorBtn=uicontrol('Style','checkbox','String','Use Baseline Correction',...
%	'FontSize', 14,...
%	'Position', [xText1Pos+x2Pos y2Pos 200 20]);
 
Chan1=uicontrol('Style','checkbox','String','Channel 1',...
    'FontSize', 14,...
    'Position', [xText1Pos+x2Pos+150 y2Pos-130 200 20]);
set(Chan1, 'Value',1);
 
Chan2=uicontrol('Style','checkbox','String','Channel 2',...
    'FontSize', 14,...
    'Position', [xText1Pos+x2Pos+150 y2Pos-y2space-110 200 20]);
 set(Chan2, 'Value',0);
 
 Chan2Short=uicontrol('Style','checkbox','String','Channel 2 (quick)',...
    'FontSize', 14,...
    'Position', [xText1Pos+x2Pos+150 y2Pos-y2space-140 200 20]);
 set(Chan2Short, 'Value',0);

%% Pushbutton callback for the "Analyze Button"
AnalyzeBtn=uicontrol('Style','pushbutton','String','ANALYZE',...
    'Position', [380 110 200 140],...
    'BackgroundColor', [.2 .7 .2],...
    'ForegroundColor', [1 1 1],...
    'FontSize', 35,...
    'FontWeight', 'bold',...
    'Callback',@p_call);
 
    function p_call(varargin)
    	%baseline = get(BkgndCorBtn,'Value');
    	%assignin('base','baseline',baseline);
    	
    	ploton = get(PlotA,'Value');
    	assignin('base','ploton',ploton);
    	
    	Histon = get(Histo,'Value');
    	assignin('base','histon',Histon);
    	
        %checkboxes 2
        
        Chan1 = get(Chan1,'Value');
    	assignin('base','Chan1',Chan1);
    	
    	Chan2 = get(Chan2,'Value');
    	assignin('base','Chan2',Chan2);
        
        Chan2Short = get(Chan2Short, 'Value');
        assignin('base','Chan2Short',Chan2Short);
    	
    	%blanks
    	fileType=get(FTypeinput,'string');
    	assignin('base','fileType',fileType);
    	
        peakDetBL1=get(PeakDBL1,'string');
    	peakDetpknum1=str2num(peakDetBL1);
    	assignin('base','peakDetBL1',peakDetpknum1);
    	
        peakDetBL2=get(PeakDBL2,'string');
    	peakDetpknum2=str2num(peakDetBL2);
    	assignin('base','peakDetBL2',peakDetpknum2);
        
    	peakDetpk1=get(PeakDPk1,'string');
    	peakDetpk1=str2num(peakDetpk1);
    	assignin('base','peakDetpk1',peakDetpk1);
        
        peakDetpk2=get(PeakDPk2,'string');
    	peakDetpk2=str2num(peakDetpk2);
    	assignin('base','peakDetpk2',peakDetpk2);
    	
    	noiseMul1=get(NoiseMul1,'string');
    	noiseMul1=str2num(noiseMul1);
    	assignin('base','noiseMul1',noiseMul1);
    	
        noiseMul2=get(NoiseMul2,'string');
    	noiseMul2=str2num(noiseMul2);
    	assignin('base','noiseMul2',noiseMul2);
        
    	peakDetDelay1=get(peakDetDelay1,'string');
    	peakDetDelay1=str2num(peakDetDelay1);
    	assignin('base','peakDetDelay1',peakDetDelay1);
        
        peakDetDelay2=get(peakDetDelay2,'string');
    	peakDetDelay2=str2num(peakDetDelay2);
    	assignin('base','peakDetDelay2',peakDetDelay2);
    	
    	peakDetPostBL1=get(peakDetPostBL1,'string');
    	peakDetPostBL1=str2num(peakDetPostBL1);
    	assignin('base','peakDetPostBL1',peakDetPostBL1);
        
        peakDetPostBL2=get(peakDetPostBL2,'string');
    	peakDetPostBL2=str2num(peakDetPostBL2);
    	assignin('base','peakDetPostBL2',peakDetPostBL2);
    	
    	noiseMulDelay1=get(NoiseMulDelay1,'string');
    	noiseMulDelay1=str2num(noiseMulDelay1);
    	assignin('base','noiseMulDelay1',noiseMulDelay1);
        
        noiseMulDelay2=get(NoiseMulDelay2,'string');
    	noiseMulDelay2=str2num(noiseMulDelay2);
    	assignin('base','noiseMulDelay2',noiseMulDelay2);
    	
    	preBaseline1=get(prevBaseline1,'string');
    	preBaseline1=str2num(preBaseline1);
    	assignin('base','preBaseline1',preBaseline1);
        
        preBaseline2=get(prevBaseline2,'string');
    	preBaseline2=str2num(preBaseline2);
    	assignin('base','preBaseline2',preBaseline2);
    	
    	fileName=get(fileName,'string');
    	assignin('base','fileName',fileName);
    	
    	close gcf 
    	
    end
 
%% Pushbutton callback for the "Cancel" button
 
AnalyzeBtn2=uicontrol('Style','pushbutton','String','Cancel',...
    'Position', [380 25 160 60],...
    'BackgroundColor', [.97 .0 .2],...
    'ForegroundColor', [.97 .97 .97],...
    'FontSize', 20,...
    'FontWeight', 'bold',...
    'Callback',@cancel_call);
 
    function cancel_call(varargin)
    	
    	assignin('base','cancel',1);
    	close gcf
    end
 
waitfor(f)
 
end