function[]=textBox2()

txtf2 = figure ('menu','none',...
    'Position', [1050 700 420 150],...
    'visible','on',...
    'Resize', 'on');

set(txtf2,'name','Are you finished?','numbertitle','off')



AnalyzeBtn3=uicontrol('Style','pushbutton','String','Go back',...
    'Position', [30 40 160 60],...
    'BackgroundColor', [.6 .2 .2],...
    'ForegroundColor', [.97 .97 .97],...
    'FontSize', 24,...
    'FontWeight', 'bold',...
    'Callback',@cancel_call2);

    function cancel_call2(varargin)
        
        assignin('base','cancel3',1);
        close gcf
    end

AnalyzeBtn3=uicontrol('Style','pushbutton','String','Done',...
    'Position', [230 40 160 60],...
    'BackgroundColor', [.2 .6 .2],...
    'ForegroundColor', [.97 .97 .97],...
    'FontSize', 24,...
    'FontWeight', 'bold',...
    'Callback',@cancel_call3);

    function cancel_call3(varargin)
        
        assignin('base','cancel3',3);
        close gcf
    end



waitfor(txtf2)


end

